stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/

before_script:
  - apt-get update -qy
  - apt-get install -y ssh-agent
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run frontend npm test

deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh user@your-server-ip "cd /path/to/your/app && git pull origin master && docker-compose up -d"
  environment:
    name: production
