
stages:
  # - build
  # - deploy
  - self-hosted
# build:
#   image: docker:latest
#   stage: build
#   services:
#     - docker:dind
#   script:
#     - docker-compose build
# deploy:
#   image: docker:latest
#   stage: deploy
#   services:
#     - docker:dind
#   script:
#     - docker-compose up
self-hosted:
  image: alpine:latest
  stage: self-hosted
  tags:
    - Alok2
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client openssh-server
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "pwd"
    # - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "git clone https://gitlab.com/Alok_kushal/React-docker.git"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd React-docker && docker-compose build && docker-compose up -d"